services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: user-security
      POSTGRES_PASSWORD: 1234567
    ports:
      - "5433:5432"
    volumes:
      - ./.db_data:/var/lib/postgresql/data
    networks:
      - mynetwork

networks:
  mynetwork:
    name: "mynetwork"